default:
  cluster: ecsr-test
  runner: ecs
  region: ap-northeast-1
  container_definition:
    image: joker1007/wrapbox
    cpu: 256
    memory: 256
    essential: true

docker:
  runner: docker
  keep_container: false
  container_definition:
    image: joker1007/wrapbox
    cpu: 600
    memory: 1024
