default:
  cluster: ecsr-test
  runner: ecs
  region: ap-northeast-1
  container_definition:
    image: joker1007/wrapbox
    cpu: 512
    memory: 1024
    essential: true

docker:
  runner: docker
  rm: true
  container_definition:
    image: joker1007/wrapbox
    cpu: 512
    memory: 1024
